# 방법1.
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE "%Intact%"
AND OUTS.SEX_UPON_OUTCOME NOT LIKE "%Intact%"
ORDER BY INS.ANIMAL_ID ASC;

# 방법2.
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE SEX_UPON_OUTCOME NOT LIKE "%Intact%"
AND ANIMAL_ID IN (
                    SELECT ANIMAL_ID
                    FROM ANIMAL_INS
                    WHERE SEX_UPON_INTAKE LIKE "%Intact%"
                 )
ORDER BY ANIMAL_ID ASC;